title: "Miguel Lee"
description: "ì•ˆë…•í•˜ì„¸ìš”! Web Frontend ê°œë°œì ì´ë¯¼ê¸° Miguelì…ë‹ˆë‹¤ğŸ‘¨â€ğŸ’»"
baseurl: ""
url: "http://blog.minkymiguellee.kro.kr"
name: "Miguel Lee"

futrue: true

header_pages:
  - index.md
  - miguel.md
  - miguelEn.md

style: dark

footer: "contact - zzon2004@gmail.com"

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
